[build-system]
requires = ["setuptools~=67.5", "wheel~=0.34", "cython~=3.0", "numpy~=1.24", "orjson>=3.9"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
line_length = 100

