# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Version of OmicsDS
version <- function() {
    .Call(`_omicsds_version`)
}

#' Connect to an OmicsDS workspace/array
#'
#' Get a handle to an OmicsDS instance given a workspace/array
#' Calling disconnect will release resources held
#' by the native OmicsDS.
#'
#' @param workspace path to an OmicsDS workspace
#' @param array name of the array in the OmicsDS workspace
#' @return handle representation of the OmicsDS instance for the given workspace and array
#' @export
#' @examples
#' \dontrun{
#' omicsds_handle <- omicsds::connect(workspace="~/feature-level-ws", array="18K_samples")
#' }
#'
connect <- function(workspace, array) {
    .Call(`_omicsds_connect`, workspace, array)
}

#' Disconnect from an OmicsDS workspace/array
#'
#' Disconnect from a given OmicsDS instance to release resources held by the
#' instance.
#'
#' @param handle OmicsDS instance representation for a workspace/array
#' @export
#' @examples
#' \dontrun{
#' omicsds_handle <- omicsds::connect(workspace="~/feature-level-ws", array="18K_samples")
#' omicsds::disconnect(omicsds_handle)
#' }
#'
disconnect <- function(handle) {
    invisible(.Call(`_omicsds_disconnect`, handle))
}

#' Slice OmicsDS array by features/samples
#'
#' Get a slice as a DataFrame from an OmicsDS instance referenced by handle,
#' given features and a sample range. Features and sample range can be
#' NULL, in which case all features and/or samples are returned from
#' OmicsDS.
#'
#' @param handle OmicsDS instance representation for a workspace/array
#' @param features slice by list of features or NULL for all features
#' @param sample_range slice by sample range or NULL for all samples
#' @return R data.frame for the OmicsDS workspace array sliced by features/samples
#' @export
#' @examples
#' \dontrun{
#' omicsds_handle <- omicsds::connect(workspace="~/feature-level-ws", array="18K_samples")
#' df <- omicsds::query_features(handle=omicsds_handle, features=c("ENSG00000138190", "ENSG00000243485"), sample_range=c(0, 2))
#' df1 <- omicsds::query_features(handle=omicsds_handle, features=NULL, sample_range=c(0, 2))
#' df2 <- omicsds::query_features(handle=omicsds_handle, features=c("ENSG00000138190"), sample_range=NULL)
#' df3 <- omicsds::query_features(handle=omicsds_handle, features=NULL, sample_range=NULL)
#' }
query_features <- function(handle, features = NULL, sample_range = NULL) {
    .Call(`_omicsds_query_features`, handle, features, sample_range)
}

