# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Version of OmicsDS
version <- function() {
    .Call(`_omicsds_version`)
}

#' Get a handle to an OmicsDS instance given a workspace/array
#' Calling disconnect will release resources held
#' by the native OmicsDS.
#'
#' @param workspace
#' @param array
#' @export
#' @examples
#' omicsds_handle <- omicsds::connect(workspace="~/feature-level-ws", array="18K_samples")
#'
connect <- function(workspace, array) {
    .Call(`_omicsds_connect`, workspace, array)
}

#' Disconnect from a given OmicsDS instance to release resources held by the
#' instance.
#'
#' @param handle
#' @export
#' @examples
#' omicsds::disconnect(omicsds_handle)
#'
disconnect <- function(handle) {
    invisible(.Call(`_omicsds_disconnect`, handle))
}

#' Get a slice as a DataFrame from an OmicsDS instance referenced by handle,
#' given features and a sample range. Features and sample range can be
#' NULL, in which case all features and/or samples are returned from
#' OmicsDS.
#'
#' @param handle
#' @param features
#' @param sample_range
#' @export
#' @examples
#' df <- omicsds::query_features(handle=omicsds_handle, features=c("ENSG00000138190", "ENSG00000243485"), sample_range=c(0, 2))
#' df1 <- omicsds::query_features(handle=omicsds_handle, features=NULL, sample_range=c(0, 2))
#' df2 <- omicsds::query_features(handle=omicsds_handle, features=c{"ENSG00000138190"}, sample_range=NULL)
#' df3 <- omicsds::query_features(handle=omicsds_handle, features=NULL, sample_range=NULL)
query_features <- function(handle, features = NULL, sample_range = NULL) {
    .Call(`_omicsds_query_features`, handle, features, sample_range)
}

rcpp_hello_world <- function() {
    .Call(`_omicsds_rcpp_hello_world`)
}

rcpp_vector_access1 <- function() {
    invisible(.Call(`_omicsds_rcpp_vector_access1`))
}

