name: Docker build

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
    secrets:
      DOCKER_REGISTRY:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_TOKEN:
        required: true
      DEVELOPER_TOKEN:
        required: true

jobs:
  docker-build:
    name: Docker build
    runs-on: ${{ inputs.runner }}
    steps:
    - uses: actions/checkout@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build & test docker
      env:
        DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
        DEVELOPER_TOKEN: ${{ secrets.DEVELOPER_TOKEN }}
      run: |
        git lfs pull
        .github/scripts/build_dockers.sh
